# .github/workflows/cleanup.yml
# This workflow runs a script to clean up orphaned users from the database.

name: Clean Up Orphaned Database Users

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  schedule:
    # Runs every minute.
    - cron: '*/1 * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # The following steps now run in the root of the checked-out repository,
      # which is the correct location.
      - name: Create Service Account Key File from Secret
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json

      - name: Install Dependencies for Sync Script
        run: npm install firebase-admin

      - name: Run the User Cleanup Script
        run: node syncUsers.js