# .github/workflows/cleanup.yml
# This workflow runs a script to clean up orphaned users from the database.

name: Clean Up Orphaned Database Users

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  schedule:
    # Runs every minute. Please be mindful of your Actions usage limits.
    - cron: '* * * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # NEW: We must tell npm where to find the package.json to install dependencies.
      # The package.json will be created by the npm install command.
      - name: Install Dependencies for Sync Script
        run: npm install firebase-admin
        working-directory: ./Society-Poems-5e760502de27caf2fde997197d1e0e9b53dc179e

      # UPDATED: We now give the full path to the script.
      - name: Run the User Cleanup Script
        run: node Society-Poems-5e760502de27caf2fde997197d1e0e9b53dc179e/syncUsers.js

      # Note: We are no longer creating the service account key file,
      # as the script will look for it in its own directory.
      # Make sure the `serviceAccountKey.json` is in the same folder as `syncUsers.js`.
      # The secret will need to be re-created in your GitHub repo settings if it's not already there.