# .github/workflows/cleanup.yml
# This workflow runs a script to clean up orphaned users from the database.

name: Clean Up Orphaned Database Users

on:
  workflow_dispatch: # Allows you to run this manually from the Actions tab
  schedule:
    # Runs automatically on your chosen schedule.
    - cron: '* */12 * * *'

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Corrected Step:
      # `cd` all the way to UserManagement directory.
      - name: Run Cleanup Script in Correct Directory
        run: |
          cd UserManagement
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}' > serviceAccountKey.json
          npm install firebase-admin
          node syncUsers.js